# Supervized Learning with scikit-learn

Project built following a course of Datacamp to learn how to solve a classification problem using supervised learning techniques. Here we use scikit-learn to classify the party affiliation of United States Congressmen based on their voting records in 1984.

## EDA
We first start with some Exploratory Data Analysis.

In [4]:
# We first import the dataset as a pandas dataframe.
import pandas as pd
df = pd.read_csv('house-votes-84.csv', )

In [5]:
df.head()

   republican  n  y n.1 y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
0  republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   ?
1    democrat  ?  y   y   ?   y   y   n   n   n   n  y   n   y   y   n   n
2    democrat  n  y   y   n   ?   y   n   n   n   n  y   n   y   n   n   y
3    democrat  y  y   y   n   y   y   n   n   n   n  y   ?   y   y   y   y
4    democrat  n  y   y   n   y   y   n   n   n   n  n   n   y   y   y   y

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 17 columns):
republican    434 non-null object
n             434 non-null object
y             434 non-null object
n.1           434 non-null object
y.1           434 non-null object
y.2           434 non-null object
y.3           434 non-null object
n.2           434 non-null object
n.3           434 non-null object
n.4           434 non-null object
y.4           434 non-null object
?             434 non-null object
y.5           434 non-null object
y.6           434 non-null object
y.7           434 non-null object
n.5           434 non-null object
y.8           434 non-null object
dtypes: object(17)
memory usage: 57.7+ KB